sensio_todo:
    resource: "@SensioTodoBundle/Controller/"
    type:     annotation
    prefix:   /

sensio_training:
    resource: "@SensioTrainingBundle/Controller/"
    type:     annotation
    prefix:   /training

